"""Author: DEVADATH H K

Project: Quantum RL Noise Mitigation

Parameter-shift gradient estimation for quantum policy gradients."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Iterable

import numpy as np

if TYPE_CHECKING:
    from agent.quantum_policy import QuantumPolicyNetwork
    from src.runtime_executor import QuantumRuntimeExecutor

@dataclass(slots=True)
class GradientEstimatorConfig:
    """
    Configuration for parameter-shift gradients.

    For gates generated by Pauli operators, the derivative is exact:
    d f(theta) / d theta = (f(theta + pi/2) - f(theta - pi/2)) / 2.
    """

    shift: float = np.pi / 2.0

class ParameterShiftGradientEstimator:
    """Exact policy-gradient estimator based on the parameter-shift rule."""

    def __init__(self, config: GradientEstimatorConfig | None = None) -> None:
        self.config = config or GradientEstimatorConfig()

    def estimate_log_prob_gradient(
        self,
        policy: QuantumPolicyNetwork,
        executor: QuantumRuntimeExecutor,
        state: int,
        action: int,
        parameters: np.ndarray,
    ) -> np.ndarray:
        """
        Estimate gradient of log pi(a|s) with parameter shift.

        Returns:
            Gradient vector matching policy parameter dimension.
        """
        theta = np.asarray(parameters, dtype=float)
        num_params = theta.size
        shift = self.config.shift
        
        # Compute baseline probabilities
        from utils.qiskit_helpers import softmax
        baseline_logits = policy.expectation_logits(state, theta, executor)
        p = softmax(baseline_logits, temperature=policy.config.temperature)
        
        shifted_params = np.zeros((num_params * 2, num_params), dtype=float)
        for i in range(num_params):
            shifted_params[2*i] = theta.copy()
            shifted_params[2*i][i] += shift
            shifted_params[2*i+1] = theta.copy()
            shifted_params[2*i+1][i] -= shift
            
        states = [state] * (num_params * 2)
        shifted_logits = policy.batched_expectation_logits(
            states=states,
            parameters_batch=shifted_params,
            executor=executor
        )
        
        # d_log_pi_d_L_j = (1 / T) * (delta_{aj} - p_j)
        d_log_pi_d_L = -p.copy()
        d_log_pi_d_L[action] += 1.0
        d_log_pi_d_L /= policy.config.temperature
        
        gradients = np.zeros_like(theta)
        for i in range(num_params):
            plus_logits = shifted_logits[2*i]
            minus_logits = shifted_logits[2*i + 1]
            grad_L_wrt_theta_i = 0.5 * (plus_logits - minus_logits)
            gradients[i] = np.dot(grad_L_wrt_theta_i, d_log_pi_d_L)
            
        return gradients

    def estimate_reinforce_gradient(
        self,
        policy: QuantumPolicyNetwork,
        executor: QuantumRuntimeExecutor,
        states: Iterable[int],
        actions: Iterable[int],
        returns: Iterable[float],
        parameters: np.ndarray,
        entropy_coeff: float = 0.01,
    ) -> tuple[np.ndarray, float]:
        """
        Estimate full REINFORCE loss gradient over an episode trajectory.

        Loss:
            L(theta) = - sum_t [ G_t * log pi_theta(a_t | s_t) + beta * H(pi_theta(s_t)) ]
        """
        states_list = list(states)
        actions_list = list(actions)
        returns_list = list(returns)
        
        T = len(states_list)
        if T == 0:
            return np.zeros_like(parameters), 0.0
            
        theta = np.asarray(parameters, dtype=float)
        num_params = theta.size
        shift = self.config.shift
        
        # 1. Compute baseline logits for loss and probabilities
        baseline_logits = policy.batched_expectation_logits(
            states=states_list,
            parameters_batch=theta,
            executor=executor
        )
        # Handle both single-step and multi-step trajectories
        baseline_logits = np.atleast_2d(baseline_logits)
        if baseline_logits.shape[0] != T and T == 1:
            # If batched_expectation_logits returns (M,) for single state, at_least_2d makes it (1, M)
            pass
        elif baseline_logits.shape[0] != T:
            # This shouldn't happen with correct batching, but for safety:
            baseline_logits = baseline_logits.reshape(T, -1)
        
        loss = 0.0
        probs = np.zeros_like(baseline_logits)
        from utils.qiskit_helpers import softmax
        
        for t in range(T):
            p = softmax(baseline_logits[t], temperature=policy.config.temperature)
            probs[t] = p
            action = actions_list[t]
            ret = returns_list[t]
            
            # Policy gradient term
            loss += -float(ret) * np.log(np.clip(p[action], 1e-9, 1.0))
            # Entropy term (H = -sum p log p)
            entropy = -np.sum(p * np.log(p + 1e-9))
            loss -= entropy_coeff * entropy
            
        # 2. Batch gradient computation for expectations
        # (Rest remains same, we will apply entropy correction in step 3)
        shifted_params = np.zeros((num_params * 2, num_params), dtype=float)
        for i in range(num_params):
            shifted_params[2*i] = theta.copy()
            shifted_params[2*i][i] += shift
            shifted_params[2*i+1] = theta.copy()
            shifted_params[2*i+1][i] -= shift
            
        batch_states = []
        for t in range(T):
            batch_states.extend([states_list[t]] * (num_params * 2))
            
        batch_params = np.tile(shifted_params, (T, 1))
        
        shifted_logits = policy.batched_expectation_logits(
            states=batch_states,
            parameters_batch=batch_params,
            executor=executor
        )
        shifted_logits = np.atleast_2d(shifted_logits).reshape(T * num_params * 2, -1)
        
        total_grad = np.zeros_like(theta)
        
        # 3. Apply chain rule with entropy
        for t in range(T):
            action = actions_list[t]
            ret = returns_list[t]
            p = probs[t]
            temp = policy.config.temperature
            
            # Grad of log pi(a|s) wrt logits L_j:
            # d_log_pi_d_L_j = (1/T) * (delta_aj - p_j)
            d_log_pi_d_L = -p.copy()
            d_log_pi_d_L[action] += 1.0
            d_log_pi_d_L /= temp
            
            # Grad of Entropy H wrt logits L_j:
            # dH/dL_j = - (1/T) * p_j * (log p_j - sum_k p_k log p_k)
            #         = - (1/T) * p_j * (log p_j + H)
            avg_log_p = np.sum(p * np.log(p + 1e-9))
            d_H_d_L = - (p * (np.log(p + 1e-9) - avg_log_p)) / temp
            
            # Combined loss gradient wrt logits:
            # d_Loss_d_L = -G_t * d_log_pi_d_L - beta * d_H_d_L
            d_Loss_d_L = -float(ret) * d_log_pi_d_L - entropy_coeff * d_H_d_L
            
            base_idx = t * num_params * 2
            
            grad_L_wrt_theta = np.zeros((num_params, policy.n_actions), dtype=float)
            for i in range(num_params):
                plus_logits = shifted_logits[base_idx + 2*i]
                minus_logits = shifted_logits[base_idx + 2*i + 1]
                grad_L_wrt_theta[i] = 0.5 * (plus_logits - minus_logits)
                
            total_grad += grad_L_wrt_theta @ d_Loss_d_L
            
        return total_grad, float(loss)

