"""Parameter-shift gradient estimation for measurement-defined quantum policies."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, TYPE_CHECKING

import numpy as np

from utils.qiskit_helpers import project_probabilities

if TYPE_CHECKING:
    from agent.quantum_policy import QuantumPolicyNetwork
    from src.runtime_executor import QuantumRuntimeExecutor


@dataclass(slots=True)
class GradientEstimatorConfig:
    """
    Configuration for parameter-shift gradients.

    For gates generated by Pauli operators, the derivative of the ideal circuit
    probability is analytic:
    d p(a | s, theta) / d theta_i = (p(a | s, theta_i + pi/2) - p(a | s, theta_i - pi/2)) / 2.

    Under finite shots, noise, or mitigation, the chain rule is unchanged but
    the resulting estimator is stochastic.
    """

    shift: float = np.pi / 2.0


class ParameterShiftGradientEstimator:
    """Policy-gradient estimator for a measurement-defined quantum policy."""

    def __init__(self, config: GradientEstimatorConfig | None = None) -> None:
        self.config = config or GradientEstimatorConfig()

    def estimate_log_prob_gradient(
        self,
        policy: QuantumPolicyNetwork,
        executor: QuantumRuntimeExecutor,
        state: int,
        action: int,
        parameters: np.ndarray,
    ) -> np.ndarray:
        """Estimate grad_theta log pi(a|s) from parameter-shifted action probabilities."""
        theta = np.asarray(parameters, dtype=float)
        num_params = theta.size
        shift = self.config.shift

        baseline_probs = project_probabilities(
            np.asarray(policy.action_probabilities(state, theta, executor), dtype=float),
        )

        shifted_params = np.zeros((num_params * 2, num_params), dtype=float)
        for idx in range(num_params):
            shifted_params[2 * idx] = theta.copy()
            shifted_params[2 * idx][idx] += shift
            shifted_params[2 * idx + 1] = theta.copy()
            shifted_params[2 * idx + 1][idx] -= shift

        shifted_probs = np.asarray(
            policy.batched_action_probabilities(
                states=[state] * (num_params * 2),
                parameters_batch=shifted_params,
                executor=executor,
            ),
            dtype=float,
        ).reshape(num_params * 2, policy.n_actions)

        gradients = np.zeros_like(theta)
        normalizer = max(float(baseline_probs[action]), 1e-9)
        for idx in range(num_params):
            plus_probs = shifted_probs[2 * idx]
            minus_probs = shifted_probs[2 * idx + 1]
            grad_p = 0.5 * (plus_probs - minus_probs)
            gradients[idx] = grad_p[action] / normalizer
        return gradients

    def estimate_reinforce_gradient(
        self,
        policy: QuantumPolicyNetwork,
        executor: QuantumRuntimeExecutor,
        states: Iterable[int],
        actions: Iterable[int],
        weights: Iterable[float],
        parameters: np.ndarray,
        entropy_coeff: float = 0.01,
        probability_floor: float = 0.0,
    ) -> tuple[np.ndarray, float]:
        """
        Estimate the gradient of a REINFORCE-style surrogate over a trajectory.

        The scalar weights are typically reward-to-go returns G_t or advantages
        A_t = G_t - b_t with an action-independent baseline b_t.
        """
        states_list = list(states)
        actions_list = list(actions)
        weights_list = list(weights)

        horizon = len(states_list)
        if horizon == 0:
            return np.zeros_like(parameters), 0.0

        theta = np.asarray(parameters, dtype=float)
        num_params = theta.size
        shift = self.config.shift

        baseline_probs = np.asarray(
            policy.batched_action_probabilities(
                states=states_list,
                parameters_batch=theta,
                executor=executor,
            ),
            dtype=float,
        )
        baseline_probs = np.atleast_2d(baseline_probs)
        if baseline_probs.shape[0] != horizon:
            baseline_probs = baseline_probs.reshape(horizon, -1)
        baseline_probs = project_probabilities(baseline_probs, floor=probability_floor)

        loss = 0.0
        clipped_probs = np.clip(baseline_probs, 1e-9, 1.0)
        for timestep, action in enumerate(actions_list):
            probs = clipped_probs[timestep]
            weight = float(weights_list[timestep])
            entropy = -np.sum(probs * np.log(probs))
            loss += -weight * np.log(probs[action])
            loss -= entropy_coeff * entropy

        shifted_params = np.zeros((num_params * 2, num_params), dtype=float)
        for idx in range(num_params):
            shifted_params[2 * idx] = theta.copy()
            shifted_params[2 * idx][idx] += shift
            shifted_params[2 * idx + 1] = theta.copy()
            shifted_params[2 * idx + 1][idx] -= shift

        batch_states: list[int] = []
        for state in states_list:
            batch_states.extend([state] * (num_params * 2))
        batch_params = np.tile(shifted_params, (horizon, 1))

        shifted_probs = np.asarray(
            policy.batched_action_probabilities(
                states=batch_states,
                parameters_batch=batch_params,
                executor=executor,
            ),
            dtype=float,
        ).reshape(horizon * num_params * 2, policy.n_actions)

        total_grad = np.zeros_like(theta)
        for timestep, action in enumerate(actions_list):
            probs = clipped_probs[timestep]
            weight = float(weights_list[timestep])
            base_idx = timestep * num_params * 2

            grad_p_wrt_theta = np.zeros((num_params, policy.n_actions), dtype=float)
            for idx in range(num_params):
                plus_probs = shifted_probs[base_idx + 2 * idx]
                minus_probs = shifted_probs[base_idx + 2 * idx + 1]
                grad_p_wrt_theta[idx] = 0.5 * (plus_probs - minus_probs)

            log_prob_grad = -weight * grad_p_wrt_theta[:, action] / max(float(probs[action]), 1e-9)
            entropy_grad = entropy_coeff * (grad_p_wrt_theta @ (np.log(probs) + 1.0))
            total_grad += log_prob_grad + entropy_grad

        return total_grad, float(loss)
